name: 'Terraform Apply'
description: "terraform apply for GCP"
inputs:
  base64_workload_identity_provider:
    description: GCP Workload Identity Pool Provider ID (e.g. projects/<project-number>/locations/global/workloadIdentityPools/<pool>/providers/<id>)
    required: true
  base64_gcp_service_account:
    description: GCP service Acccount to authenticate with using workload identity
    required: true
  base64_terraform_project_id:
    description: Base64 encoded GCP project id of the folder's terraform state project
    required: true
  base64_domain_project_id:
    description: Base64 encoded GCP project id of the stack's domain
    required: true
  secrets_provisioning_private_key:
    description: Private key for a GitHub App that can provision repo-environments and secrets
    required: true
  additional_apply_args:
    description: Additional arguments to add to the `terraform apply` step. Use this to specify tfvar files, for example
    required: false
    default: ""
  use_plan_file:
    description: Whether to use the plan file from the `terraform plan` step. May not be compatible with additional_apply_args
    required: false
    default: "false"
  tf_working_dir:
    description: Path to directory where terraform commands should be run
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Set up gcloud
      uses: vivantehealth/gcloud-workload-identity-action@v2
      with:
        base64_workload_identity_provider: ${{ inputs.base64_workload_identity_provider }}
        base64_gcp_service_account: ${{ inputs.base64_gcp_service_account }}
    - name: Set up Terraform cli
      uses: hashicorp/setup-terraform@v1
    - name: Generate backend config
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: |
        echo "bucket = \"$(echo -n ${{ inputs.base64_terraform_project_id }} | base64 -d)-state\"" > backend.hcl
        echo "prefix = \"${{ github.event.repository.name }}\"" >> backend.hcl
        cat backend.hcl
    - name: TF init
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: terraform init -input=false -backend-config=./backend.hcl
    - name: TF apply
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: |
        export TF_VAR_stack_name=$(echo -n ${{ github.event.repository.name }})
        export TF_VAR_domain_project_id=$(echo -n ${{ inputs.base64_domain_project_id }} | base64 -d)
        export TF_VAR_terraform_project_id=$(echo -n ${{ inputs.base64_terraform_project_id }} | base64 -d)
        if [[ ${{ inputs.use_plan_file }} == "true" ]]; then
          terraform apply -input=false ${{ inputs.additional_apply_args }} planfile
        else
          terraform apply -input=false -auto-approve ${{ inputs.additional_apply_args }}
        fi
      env:
        TF_VAR_secrets_provisioning_private_key: ${{ inputs.secrets_provisioning_private_key }}
