name: 'Terraform Apply'
description: "terraform apply for GCP"
inputs:
  gcp_key:
    description: GCP key of a service account that has at least read permissions to the resources managed by the terraform files
    required: true
  base64_terraform_project_id:
    description: Base64 encoded GCP project id of the folder's terraform state project
    required: true
  base64_domain_project_id:
    description: Base64 encoded GCP project id of the stack's domain
    required: true
  secrets_provisioning_private_key:
    description: Private key for a GitHub App that can provision repo-environments and secrets
    required: true
  additional_apply_args:
    description: Additional arguments to add to the `terraform apply` step. Use this to specify tfvar files, for example
    required: false
    default: ""
  use_plan_file:
    description: Whether to use the plan file from the `terraform plan` step. May not be compatible with additional_apply_args
    required: false
    default: "false"
  tf_working_dir:
    description: Path to directory where terraform commands should be run
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Login to GCP
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ inputs.gcp_key }}
        export_default_credentials: true
    - name: Set up Terraform cli
      uses: hashicorp/setup-terraform@v1
    - name: just echo
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: |
        echo "${{ inputs.additional_apply_args }}"
    - name: just echo
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: |
        echo "${{ inputs.gcp_key }}"
    - name: just echo
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: |
        echo "${{ inputs.tf_working_dir }}"
    - name: just echo
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: |
        echo "${{ inputs.base64_terraform_project_id }}"
    - name: double base64
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: |
        echo "${{ inputs.base64_terraform_project_id }}" | base64 | base64
    - name: just set a variable
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: |
        base64_project="${{ inputs.base64_terraform_project_id }}" #"
    - name: just echo and base64 decode
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: |
        echo -n ${project} | base64 -d
    - name: Generate backend config
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: |
        base64_project="${{ inputs.base64_terraform_project_id }}"
        project="$(echo -n ${base64_project} | base64 -d)"
        echo "${project}"
        touch backend.hcl
    - name: Generate backend config
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: |
        echo "bucket = \"$(echo -n ${{ inputs.base64_terraform_project_id }} | base64 -d)-state\"" > backend.hcl
    - name: Continue generating backend config
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: |
        echo "prefix = \"${{ github.event.repository.name }}\"" >> backend.hcl
    - name: Debug
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: |
        cat backend.hcl
    - name: TF init
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: terraform init -input=false -backend-config=./backend.hcl
    - name: TF apply
      working-directory: ${{ inputs.tf_working_dir }}
      shell: bash
      run: |
        export TF_VAR_domain_project_id=$(echo -n ${{ inputs.base64_domain_project_id }} | base64 -d)
        export TF_VAR_terraform_project_id=$(echo -n ${{ inputs.base64_terraform_project_id }} | base64 -d)
        if [[ ${{ inputs.use_plan_file }} == "true" ]]; then
          terraform apply -input=false ${{ inputs.additional_apply_args }} planfile
        else
          terraform apply -input=false -auto-approve ${{ inputs.additional_apply_args }}
        fi
      env:
        TF_VAR_secrets_provisioning_private_key: ${{ inputs.secrets_provisioning_private_key }}
